# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'facebook.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy Dev
        
  deploy-hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
      url: 'facebook.com'
    needs: deploy-dev
    steps:
      - name: Run a one-line script
        run: echo Deploy HMG
        
  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: 'facebook.com'
    needs: deploy-hmg
    steps:
      - name: Run a one-line script
        run: echo Deploy PRD
